azure:
    url: ${AZURE_URL:none}
    openApiKey: ${OPEN_API_KEY:none}
    chatGptVersion: ${CHAT_GPT_VERSION:none}

proxy:
    host: ${PROXY_URL:none}
    port: 8080
    enabled: ${ENABLE_PROXY:false}
jira:
    userName: ${JIRA_USER_NAME:none}
    password: ${JIRA_PASSWORD:none}
    baseUrl: ${JIRA_URL:none}